import{o as r,c as l,k as a,e,aa as t,q as u,s as c,B as s}from"./modules/vue-CkRw1msW.js";import{I as p}from"./slidev/default-BM4UqsZv.js";import{u as d,f as m}from"./slidev/context-CPmvhIBt.js";import"./index-Dw6i22Y2.js";import"./modules/shiki-BK3Hl-Nn.js";const F={__name:"slides.md__slidev_8",setup(f){const{$slidev:x,$nav:g,$clicksContext:o,$clicks:h,$page:_,$renderContext:k,$frontmatter:i}=d();return o.setup(),(v,n)=>(r(),l(p,u(c(s(m)(s(i),7))),{default:a(()=>n[0]||(n[0]=[e("h1",null,"throw",-1),e("h4",null,'Mit der throw Funktion kann eine eigene Fehlermeldung erstellt werden. Man verwendet es mit sogennanten "Exception Klassen". Es gibt in C# sehr viele davon.',-1),e("h4",null,[t("Hier sind einige Beispiele: "),e("strong",null,"ArithmeticException"),t(", "),e("strong",null,"FileNotFoundException"),t(", "),e("strong",null,"IndexOutOfRangeException"),t(", "),e("strong",null,"TimeOutException"),t(", etc.")],-1),e("p",null,"Auf der nÃ¤chsten seite befindet sich ein Beispiel ->",-1)])),_:1},16))}};export{F as default};
